CREATE DATABASE IF NOT EXISTS PRODUCTMANAGEMENT;
USE PRODUCTMANAGEMENT;
#Armazenar marcas de sapatos que o cliente vende
CREATE TABLE MARCA(
ID_MARCA INT PRIMARY KEY AUTO_INCREMENT NOT NULL, 
NOME_MARCA VARCHAR(75)
);

#Armazenar os modelos que o cliente vende
CREATE TABLE MODELO(
ID_MODELO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
NOME_MODELO VARCHAR(75)
);

#Armazenar dados de produtos que são vendidos pelo cliente
CREATE TABLE PRODUTO(
PROD_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
PROD_NOME VARCHAR(255),
PROD_TAM INT NOT NULL,
PROD_COR VARCHAR(20),
PROD_MODELO INT, #Chave estrangeira
PROD_MARCA INT #Chave estrangeira 
);

ALTER TABLE PRODUTO ADD FOREIGN KEY (PROD_MARCA) REFERENCES MARCA(ID_MARCA);
ALTER TABLE PRODUTO ADD FOREIGN KEY (PROD_MODELO) REFERENCES MODELO(ID_MODELO);

#Salvar as alteraçoes de preço para cada produto. Se houve  aumento ou redução 
CREATE TABLE PRECOPRODUTO(
COD_PRODUTO INT, #Chave estrangeira
ID_PRECO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
PREC_UNIDADE DECIMAL(15,2),
PREC_STATUS VARCHAR(5),
DATA_REGISTRO DATE
);

ALTER TABLE PRECOPRODUTO ADD FOREIGN KEY (COD_MARCA) REFERENCES MARCA(ID_MARCA);
ALTER TABLE PRECOPRODUTO ADD FOREIGN KEY (COD_MODELO) REFERENCES MODELO(ID_MODELO);
ALTER TABLE PRECOPRODUTO ADD FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(PROD_ID);

#Salvar a quantidade de produtos disposniveis
CREATE TABLE ESTOQUE(
COD_ESTOQUE INT PRIMARY KEY AUTO_INCREMENT NOT NULL, 
COD_PRODUTO INT, #Chave estrangeira
COD_MARCA INT,#Chave estrangeira
COD_MODELO INT,#Chave estrangeira
QTD_ENTRADAPRODUTO INT NOT NULL, 
VALOR_TOTALEST DECIMAL(15,2),
USRID_ENTRADA INT NOT NULL,
DATA_ENTRADAES DATE
);

ALTER TABLE ESTOQUE ADD FOREIGN KEY (COD_MARCA) REFERENCES MARCA(ID_MARCA);
ALTER TABLE ESTOQUE ADD FOREIGN KEY (COD_MODELO) REFERENCES MODELO(ID_MODELO);
ALTER TABLE ESTOQUE ADD FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(PROD_ID);

#Salvar dados da quantidade de saida dos produtos em estoque
CREATE TABLE SAIDAESTOQUE(
COD_SAIDA INT PRIMARY KEY AUTO_INCREMENT NOT NULL, 
COD_PRODUTO INT,
QTD_SAIDAPRODUTO INT NOT NULL,
VALOR_SAIDAES DECIMAL(15,2),
USRID_RETIRADA INT NOT NULL,
DATA_SAIDAES DATE
);

#Salvar dados dos usuários que vão utilizar o sistema
CREATE TABLE USUARIOS(
USR_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
USR_NOME VARCHAR(100),
USR_TELEFONE VARCHAR(20),
USR_EMAIL VARCHAR(90),
USR_CPF VARCHAR(20),
USR_FUNCAO VARCHAR(75),
USR_ESTADO VARCHAR(10),
USR_CIDADE VARCHAR(50),
USR_BAIRRO VARCHAR(50),
USR_RUA VARCHAR(50),
USR_STATUS VARCHAR(5)
);

#Salvar dados de Grupos do sistema(Os grupos delimitam quais telas e comandos são permitidos)
CREATE TABLE GROUPUSSISTEMA(
GRP_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
GRP_NOMEGRUPO VARCHAR(75), 
GRP_DESC VARCHAR(100),
GRP_PERM INT NOT NULL,
GRP_STATUS VARCHAR(5)
);

#Armazena dados de login para cada usuario
CREATE TABLE USSISTEMA(
US_ID INT NOT NULL ,#Chave estrangeira
US_LOGIN VARCHAR(20),
US_SENHA VARCHAR(20),
US_STATUS VARCHAR(5),
US_GROUPID INT #Chave estrangeira
);

ALTER TABLE USSISTEMA ADD FOREIGN KEY (US_ID) REFERENCES USUARIOS(USR_ID);
ALTER TABLE USSISTEMA ADD FOREIGN KEY (US_GROUPID) REFERENCES GROUPUSSISTEMA(GRP_ID);

