USE PRODUCTMANAGEMENT;

INSERT INTO SAIDAESTOQUE(COD_PRODUTO,QTD_SAIDAPRODUTO,VALOR_SAIDAES,USRID_RETIRADA,DATA_SAIDAES) VALUES(1,10, 250.00, 3, '2021-04-15' );
#Quando for inserido um novo dado é retirado na quantidade de estoque#
DROP TRIGGER TRG_ATUALIZA_TABELA_ESTOQUE;
DELIMITER $$
CREATE TRIGGER TRG_ATUALIZA_TABELA_ESTOQUE AFTER INSERT ON SAIDAESTOQUE
FOR EACH ROW
BEGIN
      IF NEW.COD_SAIDA IS NOT NULL THEN
      UPDATE ESTOQUE  
      SET QTD_ENTRADAPRODUTO  = NEW.QTD_SAIDAPRODUTO - QTD_ENTRADAPRODUTO
      AND VALOR_TOTALEST = NEW.VALOR_SAIDAES - VALOR_TOTALEST
      WHERE COD_PRODUTO = NEW.COD_PRODUTO;
      END IF;
END $$
DELIMITER ;



#Quando for informado um novo preço deve ser desativado o outro#
DROP TRIGGER TRG_ATU_TAB_PRECOPRODUTO;
DELIMITER $$
CREATE TRIGGER TRG_ATU_TAB_PRECOPRODUTO BEFORE INSERT ON PRECOPRODUTO
FOR EACH ROW
BEGIN
      IF NEW.COD_PRODUTO IS NOT NULL THEN
		  UPDATE PRECOPRODUTO  
		  SET PREC_STATUS  = 'I'#Preco inativo
		  WHERE COD_PRODUTO = NEW.COD_PRODUTO;
      END IF;
END $$
DELIMITER ;